language: php

os: linux

dist: trusty

services: docker

php:
  - 7.4
  - 7.3
  - 7.2
  - 5.6

env:
  - WP_VERSION=5.4
  - WP_VERSION=5.3

jobs:
  fast_finish: true

  include:
    - php: 5.6
      env: WP_VERSION=5.4
    - php: 5.6
      env: WP_VERSION=5.3
    - php: 5.6
      env: WP_VERSION=4.9
    - php: 5.6
      env: WP_VERSION=4.7
    - php: 5.5
      env: WP_VERSION=4.9
    - php: 5.5
      env: WP_VERSION=4.7
    - php: 7.4
      env: WP_VERSION=5.4 ACCEPTANCE=1

before_script:
  - mysql -e "create database IF NOT EXISTS wpemerge_tests;" -uroot
  - bash tests/bin/install.sh wpemerge_tests root '' localhost $WP_VERSION
  # WP currently only works on PHPUnit ^7, so we need to enforce this on high PHP versions.
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then composer require --dev phpunit/phpunit:^7; fi
  # On PHP 7.4+ Mockery ^0.9 will fail with 'Cannot use "parent"' errors.
  - if [[ $TRAVIS_PHP_VERSION > '7.3' ]]; then composer require --dev --update-with-all-dependencies mockery/mockery:^1; fi
  - if [[ "$ACCEPTANCE" == "1" ]]; then composer run test:acceptance:install; fi

script:
  # Check all PHP files for syntax errors.
  # The usage of bash + || exit 1 is to ensure xargs does not exit on first error.
  - find src/ \( -name '*.php' \) | xargs -n1 bash -c 'php -lf $0 || exit 1'
  # Run unit tests.
  - composer run test:unit
  # Run acceptance tests.
  - if [[ "$ACCEPTANCE" == "1" ]]; then bash wpacceptance.sh; fi

after_script:
  # Upload coverage to Scrutinizer-CI.
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./tmp/clover.xml
